[package]
name = "egui-sfml"
version = "0.1.0"
authors = ["crumblingstatue <radiantstatue@gmail.com>"]
edition = "2018"

[dependencies]
egui = { git = "https://github.com/emilk/egui.git" }
glu-sys = "0.1.4"

[dependencies.sfml]
git = "https://github.com/jeremyletang/rust-sfml.git"
default-features = false
features = ["graphics"]

[dev-dependencies]
egui_demo_lib = { git = "https://github.com/emilk/egui.git" }
